{{- if and .Values.mlUpdateStrategy.enabled (eq .Values.mlUpdateStrategy.type "embedded") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: janus-model-pvc
  labels:
    app.kubernetes.io/name: janus-pvc
spec:
  accessModes:
    - {{ .Values.mlUpdateStrategy.embedded.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mlUpdateStrategy.embedded.pvc.size }}
{{- end }}